### ISSUE TITLE
please add is_pipe to the scandir code.

### ISSUE THREAD

**Issue by karcaw** [benhoyt/scandir#104]
it should be easy to add an is_pipe to the scandir.DirEntry class, please add it.

**Comment by benhoyt** [comment]
True, it's probably easy to add. However, I want scandir to follow the Python 3.5+ standard library version of scandir, so I don't think we'll be adding this anytime soon. Also, is_pipe() is rarely used, so I think this won't be added to the stdlib either.

In the meantime, you'll need to do something like `stat.S_ISFIFO(entry.stat().st_mode)`.
