### ISSUE TITLE
scandir(dir_fd)

### ISSUE THREAD

**Issue by ThomasWaldmann** [benhoyt/scandir#108]
it looks like python (since 3.7) supports giving a directory fd to `os.scandir` instead of a directory path.

but python software can not really use that yet as having py37 as the minimum requirement is a bit too new for most systems out there.

if giving a dir_fd was supported by the scandir pypi module, could it be used for py 3.6 users instead of the builtin scandir?

**Comment by ThomasWaldmann** [comment]
being able to use a dir_fd might improve performance as well as help with avoiding race conditions.

**Comment by ThomasWaldmann** [comment]
ping?

**Comment by benhoyt** [comment]
Hi @ThomasWaldmann, thanks for the report and ping. Unfortunately I have very little time to devote to scandir right now, so I can't add this personally. I would accept a solid PR if you have any interest in doing that?

There are several features missing from the latest Python 3.x version of scandir now, see for example #60. So in many ways it's probably better to take the latest Python 3.7 (or 3.8) source code and work backward from there.

Alternatively, if you're already on 3.6, it may just be easier to figure out how to upgrade to 3.7 and get these features from the stdlib version. Definitely easier than upgrading from 2.7. :-)

**Comment by benhoyt** [comment]
As above, I still don't have a great deal of time/motivation to spend on updating scandir at this point (especially considering Python 3.7 is quite widespread now!). But if someone wants to submit a PR, I'm all ears, so I'll leave this open for now.

**Comment by benhoyt** [comment]
Actually, I'm going to close this in favor of #60, and add a note about scandir(dir_fd) there.
