### ISSUE TITLE
scandir 1.9.0 broken in Python 2.7.13

### ISSUE THREAD

**Issue by darkvertex** [benhoyt/scandir#112]
I'm using Python 2.7.13. (Can't use Python 3 for what I need this for, sorry.)

With the latest `scandir-1.9.0` release after pip-installing in a virtualenv, I get:
```
> python
Python 2.7.13 (default, Apr  3 2017, 18:26:10)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scandir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/softwareLocal/rez_python_envs/shared/2.7/0x2ebc4ae4c97970c4/lib/python2.7/site-packages/scandir.py", line 584, in <module>
    DirEntry_c = _scandir.DirEntry
AttributeError: 'module' object has no attribute 'DirEntry'
```

...yet if I `pip install scandir==1.8` in my virtualenv instead, then I get no errors:
```
> python
Python 2.7.13 (default, Apr  3 2017, 18:26:10)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scandir
```

I think something broke in 1.9.0?

**Comment by benhoyt** [comment]
Hmm, that's strange. It looks like the _scandir.c module is being compiled (as the import works as `_scandir` is not None) but it doesn't have the `DirEntry` attribute, which is added [here](https://github.com/benhoyt/scandir/blob/master/_scandir.c#L1828). Can you do `import _scandir` and then `dir(_scandir)` and send me what attributes it reports? Also, what is the values of `sys.platform`?

**Comment by darkvertex** [comment]
Sure, here you go:

```
> python
Python 2.7.13 (default, Apr  3 2017, 18:26:10)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'linux2'
>>> import _scandir
>>> dir(_scandir)
['__doc__', '__file__', '__name__', '__package__', 'scandir']
```

Indeed, it appears to be missing "DirEntry" in there. Weird!

**Comment by darkvertex** [comment]
Dammit, just looked at it with a coworker and discovered an old .so of scandir-1.5.0 that had snuck into my environment. It's working now.

Sorry about that. I'm closing this ticket.

**Comment by benhoyt** [comment]
Good to hear, thanks!

**Comment by rachel-sunrui** [comment]
Hi,

I encountered this issue too. It happened when I tried to "from scipy.io import savemat". There are not many solutions for this on the Internet, do you mind going into more details about how did you solve the problem? Thank you.

Best regards,
Rachel

**Comment by darkvertex** [comment]
I guess just `import _scandir;print _scandir` and see where it's coming from. Make sure it's a recent version.

**Comment by rachel-sunrui** [comment]
Thank you for the suggestion. However, I end up setting up a new
environment and reinstall the packages.

Best regards,
Rachel

Alan Fregtman <notifications@github.com> 于2019年6月19日周三 下午2:07写道：
