### ISSUE TITLE
test on py37?

### ISSUE THREAD

**Issue by ThomasWaldmann** [benhoyt/scandir#115]
see my comment there:

https://github.com/benhoyt/scandir/commit/27a49d958b2c07fd854f5d960cd65f6eb9a596d7

if it makes sense to test on py37, i can create a PR for it.

**Comment by benhoyt** [comment]
Yes please, let's test on py37 -- is it easy to switch to Xenial?

**Comment by ThomasWaldmann** [comment]
Usually yes, I'll make a PR and we'll see.
