### ISSUE TITLE
Fix locale/unicode test failures on FreeBSD

### ISSUE THREAD

**Issue by koobs** [benhoyt/scandir#122]
#109 (Fixing #79) resolved test failures on OpenBSD when coupled with setting the system locale to `en_US.UTF-8`

I've confirmed that #109 fixes the same issue in/on FreeBSD

All tests pass on Python 2.7,3.5-3.8 with that #109 (modified to check for `freebsd`) applied. I imagine this means a similar set of factors are involved, though I have not verified or checked those assumptions beyond ensuring the tests pass.

**Comment by benhoyt** [comment]
So this is fixed by #109, which is already merged, right? I'll close with that assumption, but if not, feel free to re-open or create a pull request.
