### ISSUE TITLE
Error from running setup.py install on python 2.7.5 win

### ISSUE THREAD

**Issue by binzb** [benhoyt/scandir#123]
setup.py:11 UserWarning: import of setuptools failed ImportError<'No module named setuptools'>
C:\Python27\lib\distutils\extension.py:133: UserWarning: Unknown Extension options: 'optinal'
WARING:root:building the _scandir failed with <class 'distutils.error.DistutilsPlatformError'>

**Comment by benhoyt** [comment]
Does this actually cause an error? In the code ([here](https://github.com/benhoyt/scandir/blob/master/setup.py#L11)) it just logs a warning and then tries to import distutils.

**Comment by binzb** [comment]
> Does this actually cause an error? In the code ([here](https://github.com/benhoyt/scandir/blob/master/setup.py#L11)) it just logs a warning and then tries to import distutils.

but the _scandir is not build ,which is the core of the scandir that could faster than listdir?

**Comment by benhoyt** [comment]
On Windows things are a bit more complex, as you have to have the MS C compiler installed etc. Does it say why it's not building the C `_scandir` -- is it because of not having the correct C compiler installed rather than this `setuputils` issue?

**Comment by binzb** [comment]
> On Windows things are a bit more complex, as you have to have the MS C compiler installed etc. Does it say why it's not building the C `_scandir` -- is it because of not having the correct C compiler installed rather than this `setuputils` issue?

Could you tell me how to install c compiler correctly? thx

**Comment by benhoyt** [comment]
You have to install the standalone [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266) - it's free. See [this guide](https://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/).
