### ISSUE TITLE
some doubt about your another project :pygit

### ISSUE THREAD

**Issue by adlternative** [benhoyt/scandir#130]
I know it’s not very polite, but your pygit project closed the issue, which let me don't how to ask que. Yes, your pygit is well written, but the final package to github will appear
`AssertionError: expected line 1 b'unpack ok', got: b'\x010024unpack index-pack abnormal exit\n'`
I don't know if you have noticed this problem again. After all, as an excellent case, the code that can't be successfully pushed will make me feel a little regretful. If there is a problem with my use, please let me know, thank you!
```
python pygit.py init testdir
cd testdir
python ../pygit.py add a.c
python ../pygit.py commit -a adl -m hehe
python ../pygit.py push https://github.com/adlternative/pygit.git -u xxxxx -p xxxxx
```

**Comment by benhoyt** [comment]
Hi @adlternative -- if you email me (see contact info at https://benhoyt.com/) we can continue this conversation via email. In the meantime, I tried to reproduce this issue and it didn't happen for me:

```
~/h$ python3 pygit/pygit.py init pygit-test
initialized empty repository: pygit-test
~/h$ cd pygit-test/
~/h/pygit-test$ python3 ../pygit/pygit.py add README.md
~/h/pygit-test$ python3 ../pygit/pygit.py commit --author 'Ben Hoyt <benhoyt@gmail.com>' -m 'Commit pygit-test README'
committed to master: a1e5a2acea3de1130ae9e2d6a1acc2bfb7f9ab9f
~/h/pygit-test$ GIT_USERNAME=benhoyt GIT_PASSWORD=xxx python3 ../pygit/pygit.py push https://github.com/benhoyt/pygit-test.git
updating remote master from no commits to a1e5a2acea3de1130ae9e2d6a1acc2bfb7f9ab9f (3 objects)
```

You can see the pygit-test repo here: https://github.com/benhoyt/pygit-test

So I'm not sure what's going on for you, sorry!

**Comment by adlternative** [comment]
> Hi @adlternative -- if you email me (see contact info at https://benhoyt.com/) we can continue this conversation via email. In the meantime, I tried to reproduce this issue and it didn't happen for me:
> 
> ```
> ~/h$ python3 pygit/pygit.py init pygit-test
> initialized empty repository: pygit-test
> ~/h$ cd pygit-test/
> ~/h/pygit-test$ python3 ../pygit/pygit.py add README.md
> ~/h/pygit-test$ python3 ../pygit/pygit.py commit --author 'Ben Hoyt <benhoyt@gmail.com>' -m 'Commit pygit-test README'
> committed to master: a1e5a2acea3de1130ae9e2d6a1acc2bfb7f9ab9f
> ~/h/pygit-test$ GIT_USERNAME=benhoyt GIT_PASSWORD=xxx python3 ../pygit/pygit.py push https://github.com/benhoyt/pygit-test.git
> updating remote master from no commits to a1e5a2acea3de1130ae9e2d6a1acc2bfb7f9ab9f (3 objects)
> ```
> 
> You can see the pygit-test repo here: https://github.com/benhoyt/pygit-test
> 
> So I'm not sure what's going on for you, sorry!

I have solved it, thank you. There is a problem with the email format filled in my commit. I need to add xxx <xxx@gamil.com>. I used to fill in my commit in the form of xxx xxx@gamil.com, which resulted in The problem of unpacking the github server during the later push.

In addition, it can be mentioned that github told me that this way of filling in the account and password through the terminal to push may have security vulnerabilities. Through git reflog, this interesting tutorial may have to be changed in August next year, haha!

**Comment by benhoyt** [comment]
Good find, thanks for the update.
