### ISSUE TITLE
The benchmark test doesn't work

### ISSUE THREAD

**Issue by stephenboulet** [benhoyt/scandir#43]
C:\Users\username\Documents\Python Scripts\scandir>python benchmark.py
Creating tree at benchtree: depth=4, num_dirs=5, num_files=50
Using fast C version of scandir
Comparing against builtin version of os.walk()
Priming the system's cache...
Traceback (most recent call last):
  File "benchmark.py", line 255, in <module>
    benchmark(tree_dir, get_size=options.size)
  File "benchmark.py", line 160, in benchmark
    do_scandir_walk()
  File "benchmark.py", line 155, in do_scandir_walk
    for root, dirs, files in scandir.walk(path):
  File "C:\Users\username\Documents\Python Scripts\scandir\scandir.py", line 604, in walk
    for entry in scandir(top):
  File "C:\Users\username\Documents\Python Scripts\scandir\scandir.py", line 405, in scandir_c
    for name, stat in scandir_helper(path):
TypeError: iter() returned non-iterator of type 'tuple'

C:\Users\username\Documents\Python Scripts\scandir>

**Comment by benhoyt** [comment]
Huh, that's really weird. Can you tell me what `scandir.scandir_helper(r"C:\Users\username")` returns?

**Comment by stephenboulet** [comment]
Thanks. It returns "<FileIterator object at 0x0000000002C72030>".

**Comment by benhoyt** [comment]
Okay, can you run `list(scandir.scandir_helper(r"C:\Users\username"))` and send through the output?

**Comment by stephenboulet** [comment]
I'm getting:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: iter() returned non-iterator of type 'tuple'

Same thing happens when I try a loop like os.walk:

for (dirpath, dirnames, filenames) in scandir.walk(root):

I get TypeError: iter() returned non-iterator of type 'tuple'

I wonder if it could be some bug in my python distribution (ython 3.4.1 |Anaconda 2.1.0 (64-bit)| (default, Sep 24 2014, 18:32:42) [MSC v.1600 64 bit (AMD64)] on win32).

**Comment by stephenboulet** [comment]
By the way, os.walk works, as does scandir.os.walk.

**Comment by benhoyt** [comment]
That's weird -- I'm not sure what's going on here. From your output above it looks like `scandir_helper()` is returning a `FileIterator`, not a `tuple`.

**Comment by stephenboulet** [comment]
Hello again. Any idea what I'm missing to be able to compile scandir?

>python setup.py install
running install
running build
running build_py
running build_ext
building '_scandir' extension
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\Python34\include -Ic:\Python34\include /Tc_scandir.c /Fobuild\temp.win-amd64-3.4\Release\_sc
andir.obj
_scandir.c
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\Python34\libs /LIBPATH:c:\Python34\PCbuild\amd64 /EXPORT:PyInit__scandir build\temp.win-amd
64-3.4\Release\_scandir.obj /OUT:build\lib.win-amd64-3.4\_scandir.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\_scandir.lib /MANIFESTFILE:build\temp.win-amd64-3.4\Release\_scandir.pyd.manifest
   Creating library build\temp.win-amd64-3.4\Release\_scandir.lib and object build\temp.win-amd64-3.4\Release\_scandir.exp
_scandir.obj : error LNK2001: unresolved external symbol _PyObject_SelfIter
_scandir.obj : error LNK2001: unresolved external symbol _PyObject_GenericGetAttr
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyErr_WarnEx referenced in function _win32_warn_bytes_api
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyExc_DeprecationWarning referenced in function _win32_warn_bytes_api
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyErr_Occurred referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyBytes_FromObject referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyErr_Clear referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyExc_ValueError referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyUnicode_AsUnicodeAndSize referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyUnicode_FromObject referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyErr_Format referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyExc_TypeError referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp___Py_NoneStruct referenced in function _path_converter
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyLong_FromUnsignedLong referenced in function _find_data_to_statresult
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyFloat_FromDouble referenced in function _find_data_to_statresult
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyLong_FromUnsignedLongLong referenced in function _find_data_to_statresult
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyLong_FromLong referenced in function _find_data_to_statresult
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyStructSequence_New referenced in function _find_data_to_statresult
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyEval_RestoreThread referenced in function __fi_close
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyEval_SaveThread referenced in function __fi_close
_scandir.obj : error LNK2019: unresolved external symbol __imp__Py_BuildValue referenced in function __fi_next
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyErr_SetFromWindowsErr referenced in function __fi_next
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyErr_NoMemory referenced in function __fi_next
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyErr_SetNone referenced in function __fi_next
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyExc_StopIteration referenced in function __fi_next
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyObject_Free referenced in function _fi_dealloc
_scandir.obj : error LNK2019: unresolved external symbol __imp___PyObject_New referenced in function __iterfile
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyArg_ParseTupleAndKeywords referenced in function _scandir_helper
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyStructSequence_InitType referenced in function _PyInit__scandir
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyType_Ready referenced in function _PyInit__scandir
_scandir.obj : error LNK2019: unresolved external symbol __imp__PyModule_Create2 referenced in function _PyInit__scandir
build\lib.win-amd64-3.4\_scandir.pyd : fatal error LNK1120: 31 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\link.exe' failed with exit status 1120

**Comment by stephenboulet** [comment]
The above was done with a fresh install of python 3.4. By the way, even though there is some C compiling subtleties I'm missing, just dropping scandir.py in the same directory as my search script gives some great improvements. os.walk did the whole walk in 6m 35s while scandir.walk cut that way down to 0m 29s. I'm a happy camper.

**Comment by benhoyt** [comment]
Great to hear that even the pure Python version is giving you a good speedup. Yeah, compiling Python extension modules on Windows is something of a dark art. I got it going several months ago, but I can't even remember how ... it involves installing VC++ and running some other stuff. I'd suggest using the Google fu.

**Comment by stephenboulet** [comment]
This page helped me to get the environment set up: http://bit.ly/1KEUoSZ. It was more involved than I thought. After that 'python setup.py install' worked just fine.
