### ISSUE TITLE
Add inodes to DirEntry objects

### ISSUE THREAD

**Issue by justin-mp** [benhoyt/scandir#44]
I recently needed to speed up code that was finding hardlinks.  The first implementation using os.walk and os.stat was too slow, so I wound up writing my on ctypes wrapper around readdir_r.  Given that the scandir project is destined for the standard library, it would be fabulous if I could throw away my code an just use scandir.  Unfortunately, scandir doesn't expose the inode number from readdir_r.  Would it be possible to add the inode number to scandir's DirEntry objects, or at least to PosixDirEntry objects on UNIX-like systems?

**Comment by benhoyt** [comment]
Unfortunately I don't think that's going to happen -- as the scandir [PEP 471](http://legacy.python.org/dev/peps/pep-0471/#specifics-of-proposal) is pretty much settled at this point. You're welcome to fork this scandir repo and add it, though!

Or maybe we can get it in as an undocumented, "use at your own risk" type of feature?

**Comment by theblacklion** [comment]
@benhoyt Would it be possible to add it like you said? Later on, if it's useful enough, it could be made official anyway.

**Comment by benhoyt** [comment]
By the way, this is happening after all! Victor Stinner (who's helping me implement and review the code for PEP 471) got this added at the last minute. It's going to be in scandir as a DirEntry.inode() method. Once I've got the CPython 3.5 implementation out of the way, I intend to update this version and back-port to Python 2.7.

**Comment by theblacklion** [comment]
Nice :)

**Comment by benhoyt** [comment]
This is done now that I've updated _scandir.c to use the Python 3.5 C code. It's faster and better, and includes the new `DirEnry.inode()` method. Available here:

* https://pypi.python.org/pypi/scandir
* https://github.com/benhoyt/scandir/releases
