### ISSUE TITLE
Cut a release/tag

### ISSUE THREAD

**Issue by stdavis** [benhoyt/scandir#45]
Would make it easier to use this repo as a dependency in my project. Thanks!

**Comment by benhoyt** [comment]
Not quite sure what you mean. A versioned tag? Note that versioned scandir releases are also on PyPI: https://pypi.python.org/pypi/scandir

**Comment by stdavis** [comment]
Yes a github tag corresponding with the latest pip version. My dependency management system requires them.

This would be awesome. Thanks!

-Scott

**Comment by benhoyt** [comment]
Done: https://github.com/benhoyt/scandir/releases/tag/v0.9

**Comment by stdavis** [comment]
Thanks!
