### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by d555** [benhoyt/scandir#46]
I've made of `scandir` one of my essential  libraries for my package `aTXT` https://pypi.python.org/pypi/aTXT , available in pypi. The issue is about how this dependency is affecting the cross-plataform issues for others developers. I mean, In a unix environment like ubuntu, or even OSX, an installation from `pip install aTXT` ( an this actually call to install `scandir`) performs well. But If I try to install on Windows (average installation settings), fails with errors about missing libraries,(vcbat) or anothers. Of course, after complete the windows requirements, `scandir` works and then aTXT too. I have users using my library in all these operative systems.  What is the best approach to deal with scandir on windows, something like a compiled version? Something to recommend me? Thanks in advance.

**Comment by benhoyt** [comment]
I don't think the issue with vcbat is a scandir problem -- it's an issue with compiling any Python C Extension on Windows (which can actually be a right pain). Have you tried following these instructions? http://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/

Also, on pypi I have a compiled version of scandir 0.9 for Python 2.7 on Windows 64-bit, in case that's the version you're after: https://pypi.python.org/pypi/scandir

**Comment by d555** [comment]
The compiled version of scandir for Windows 64-bit is enough for now. Thanks, Please, be free to close this issue.

**Comment by benhoyt** [comment]
Cool, thanks.
