### ISSUE TITLE
winreparse.h missing from PyPi package

### ISSUE THREAD

**Issue by branning** [benhoyt/scandir#48]
I attempted to install scandir from pypi:

    pip install pypi

But the build failed, it seemed to be missing `winreparse.h`

    [ijt_operation] M:\scratch\ijt_operation>pip install scandir
    Collecting scandir
      Using cached scandir-1.0.tar.gz
    Installing collected packages: scandir
      Running setup.py install for scandir
        Complete output from command C:\Miniconda\envs\ijt_operation\python.exe -c "
    import setuptools, tokenize;__file__='c:\\users\\pbranni\\appdata\\local\\temp\\
    pip-build-wlbgua\\scandir\\setup.py';exec(compile(getattr(tokenize, 'open', open
    )(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c
    :\users\pbranni\appdata\local\temp\pip-20nrru-record\install-record.txt --single
    -version-externally-managed --compile:
        running install
        running build
        running build_py
        creating build
        creating build\lib.win32-2.7
        copying scandir.py -> build\lib.win32-2.7
        running build_ext
        building '_scandir' extension
        creating build\temp.win32-2.7
        creating build\temp.win32-2.7\Release
        c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo
    /Ox /MD /W3 /GS- /DNDEBUG -IC:\Miniconda\envs\ijt_operation\include -IC:\Minicon
    da\envs\ijt_operation\PC /Tc_scandir.c /Fobuild\temp.win32-2.7\Release\_scandir.
    obj
        _scandir.c
        _scandir.c(21) : fatal error C1083: Cannot open include file: 'winreparse.h'
    : No such file or directory
        error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BI
    N\\cl.exe' failed with exit status 2

        ----------------------------------------
        Command "C:\Miniconda\envs\ijt_operation\python.exe -c "import setuptools, t
    okenize;__file__='c:\\users\\pbranni\\appdata\\local\\temp\\pip-build-wlbgua\\sc
    andir\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().r
    eplace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\pbranni\appd
    ata\local\temp\pip-20nrru-record\install-record.txt --single-version-externally-
    managed --compile" failed with error code 1 in c:\users\pbranni\appdata\local\te
    mp\pip-build-wlbgua\scandir

I found a copy of this file in the github repository, so I copied it to the include directory for the current Miniconda environment.

    [ijt_operation] M:\scratch\ijt_operation>copy winreparse.h c:\Miniconda\envs\ijt_operation\include
            1 file(s) copied.

And the pypi installation worked

    [ijt_operation] M:\scratch\ijt_operation>pip install scandir
    Collecting scandir
      Using cached scandir-1.0.tar.gz
    Installing collected packages: scandir
      Running setup.py install for scandir
    Successfully installed scandir-1.0

I'm running Miniconda from Continuum, 2.7.9 on 64-bit Windows.

**Comment by benhoyt** [comment]
Good find, thanks for the bug report! I've fixed this now in https://github.com/benhoyt/scandir/commit/186b010f61309e0cf6c74cefa2d4c61dcaed60f7 and shipped a new version (1.1) to PyPI: https://pypi.python.org/pypi/scandir
