### ISSUE TITLE
A method based on scandir that could be help others

### ISSUE THREAD

**Issue by d555** [benhoyt/scandir#49]
Thanks development team, to improve so much, this library for our comunity.
I'm working with it, and for my purposes, I had to modify the version of `scandir.walk`  a little bit.
The method has to accomplishes the following goals:
- [ ] It will work in a similiar way like `scandir.walk` with `topdown=True`,`followlinks=False`
- [ ] It will work with a level option to perform the depth-search.
- [ ] It will work like a `find` command if I specified pattern to match files (it could match folders later too)

And this is my method for above items that I'm using:
https://gist.github.com/d555/c4cd064f19692b57ccdd

```python
from scandir import scandir, islink
import os
import re


def walk(top, level=None, regex=None):
    """A modification of scandir.walk for perform
    a topdown search with level of depth and search pattern option for files
    """
    dirs = []
    nondirs = []

    if isinstance(regex, str):
        regex = re.compile(regex)

    try:
        scandir_it = scandir(top)
    except Exception:
        return

    while True:
        try:
            try:
                entry = next(scandir_it)
            except StopIteration:
                break
        except Exception:
            return

        try:
            is_dir = entry.is_dir()
        except OSError:
            is_dir = False

        if is_dir:
            dirs.append(entry.name)
        else:
            if regex is not None and hasattr(regex, 'match'):
                if regex.match(entry.name):
                    nondirs.append(entry.name)
            else:
                nondirs.append(entry.name)

    yield top, dirs, nondirs
    if level is not None:
        assert isinstance(level, int)
        if not level > 0:
            return

    for name in dirs:
        new_path = os.path.join(top, name)
        if islink(new_path):
            continue
        if isinstance(level, int):
            level -= 1
        for entry in walk(new_path, level, regex):
            yield entry


def main():
    path = os.path.expanduser('~')
    i = 1
    regex = re.compile('.*txt$')
    for r, _, f in walk(path, regex=regex):
        for file in f:
            print i, file
            if file:
                i += 1


if __name__ == "__main__":
    main()
```

and If I use, the entry given by `scandir`:

https://gist.github.com/d555/6bd50464756412505a30

Any suggestion? I will appreciate it.

**Comment by benhoyt** [comment]
Hiya! Thanks for that, nice recipe. I think you could also do this without rebuilding `walk()` by calling `os.walk()` and doing the limit by modifying `dirs` during the walk (per the documentation). For example, this function from [this StackOverflow answer](http://stackoverflow.com/a/234329) does that. And I've added a couple of lines (untested code) to filter `files` with a regex too:

    def walklevel(some_dir, level=1, regex=None):
        some_dir = some_dir.rstrip(os.path.sep)
        assert os.path.isdir(some_dir)
        num_sep = some_dir.count(os.path.sep)
        for root, dirs, files in os.walk(some_dir):
            if regex:
                files = [f for f in files if re.match(regex, f)]
            yield root, dirs, files
            num_sep_this = root.count(os.path.sep)
            if num_sep + level <= num_sep_this:
                del dirs[:]

**Comment by benhoyt** [comment]
I'm going to close this issue per above comment.
