### ISSUE TITLE
pypi v1.1 vs github 1.0 release

### ISSUE THREAD

**Issue by durack1** [benhoyt/scandir#50]
Just wondering if there are any differences between the [`pypy 1.1 release`](https://pypi.python.org/pypi/scandir) and the [`github 1.0 release`](https://github.com/benhoyt/scandir/releases/tag/v1.0).

If so are changes in the current github `master`?

**Comment by benhoyt** [comment]
Yes, there are a few minor bugfixes. I just created a v1.1 release tag on GitHub to match PyPI version 1.1. Thanks for the heads up!

**Comment by durack1** [comment]
@benhoyt thanks!
