### ISSUE TITLE
Interaction between mpi4py and scandir

### ISSUE THREAD

**Issue by fwang2** [benhoyt/scandir#52]
I am encountering an issue when using scandir in a MPI environment and not sure the cause of the issue: the reproducer is as the following `test.py`, under Python 2.7.9 on a RHEL6 box. __Note:__ that on Mac OS, I can't reproduce.

``` python
from mpi4py import MPI
#from scandir import scandir

def main():
    print "hello world"

if __name__ == "__main__": main()
```

Without importing `scandir()`, everything is fine:
```
mpirun -np 2 python test.py
```

The output is simply two lines of "hello world"

With `scandir` uncommented, the MPI warning comes in, not critical error, but enough to cause alarms for the user.

```
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.
```

The MPI library and utils (mpirun) are from OpenMPI 1.8.4 release. The casual look at the scandir implementation doesn't suggest such fork, is this something to be concerned about?

Thanks

**Comment by benhoyt** [comment]
Strange. So simply importing scandir is doing this? I know nothing about MPI, but you're right, scandir doesn't do any kind of forking. I wonder if it's the import of `ctypes` that's doing it? You could test this by changing:

    import ctypes

to

    import ctypesXYZ

in scandir.py. This will cause an ImportError, which is caught and handled by the surrounding code, and scandir will be compiled without ctypes support.

**Comment by fwang2** [comment]
Aha, you are right. After `import ctypesXYZ` and reinstall, the warning is gone! 
Am I missing anything without ctypes support? I thought scandir is a native python extension ...

**Comment by benhoyt** [comment]
It is a native C/Python extension, but it also tries to compile the ctypes version in case the C version can't be used. You can ensure the C version is in use -- if `scandir._scandir` is not None then the C version is in use. Scandir will also give you a warning at import time if neither ctypes nor the native C version can be used.

So I guess the question is, why does `import ctypes` cause this warning on MPI? Can you please take that up with the MPI folks?

**Comment by fwang2** [comment]
I will. thanks for your help. One curious thing - by not importing `ctypes` from `scandir.py` will fix the MPI warning, but importing `ctypes` directly from the test program will __not__ generate the warning:
``` python
from mpi4py import MPI
import ctytes

def main():
    print "hello world"

if __name__ == "__main__": main()
```
which is weird ... there seems to be something else going on.

**Comment by benhoyt** [comment]
That is strange. In any case, definitely seems MPI/ctypes related, so I'm going to close this issue.
