### ISSUE TITLE
32bit binary for Windows

### ISSUE THREAD

**Issue by dberansky** [benhoyt/scandir#55]
Is there a package for 32bit Python on Windows?  I can only find 64bit.

**Comment by benhoyt** [comment]
No, sorry, not here or on PyPI, at least. You'll need to build it yourself, which you should be able to do by following the instructions here, using Microsoft's special "Visual C++ Compiler for Python 2.7": http://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/

**Comment by rddaz2013** [comment]
I think Microsoft's special "Visual C++ Compiler for Python 2.7" is only working on win8+ not on XP ?
Am i right?
