### ISSUE TITLE
scandir.stat() call 

### ISSUE THREAD

**Issue by fwang2** [benhoyt/scandir#57]
hi - 

I have some question on this particular call - according to the readme:
"like os.stat(), but the return value is cached on the DirEntry object; does not require a system call on Windows (except for symlinks); don't follow symbolic links (like os.lstat()) if follow_symlinks is False"

Does it mean it won't incur system call on Window only, and it *will* incur system call on other system such as Linux?

If so, it also says "return value cached on DirEntry", is this for only Windows as well? My primary interest here to get the file size information, is it read from cache? 

TIA

**Comment by benhoyt** [comment]
Yes, it means no system call on Windows only. .stat() will do a system call
on Linux as the Linux readdir function doesn't provide that info. So
basically if you need file size you gain a lot more on Windows.

Once fetched, either at scandir time on Windows or .stat time on Linux, the
stat object is cached on the entry object.

Hope that helps.

-Ben

**Comment by fwang2** [comment]
thanks for reply. Just to be sure, if not for file size info,  .is_file()
and is_dir() check, however, will **not** incur system calls on either
windows or linux, right?

**Comment by benhoyt** [comment]
Yes, that's correct (in almost all cases -- there are edge cases like symlinks and network file systems where that may not be true on some systems).
