### ISSUE TITLE
Handle on scandir iterator on Windows

### ISSUE THREAD

**Issue by remyroy** [benhoyt/scandir#58]
On Windows, scandir will keep a handle on the directory being scanned until the iterator is exhausted. This behavior can cause various problems if try to use some filesystem calls like chmod or remove on the directory while the handle is still being kept.

This should be at least documented. Alternatively, it might be interesting to provide a way prematurely end the scan without having to exhaust it and close the handle.

**Comment by benhoyt** [comment]
That's a very good point. I guess you'll have to use regular listdir in that case. This will affect the built-in `os.scandir()` in Python 3.5 too I think -- could you please open an issue on bugs.python.org?

**Comment by remyroy** [comment]
The issue has been submitted on bugs.python.org: https://bugs.python.org/issue26111

**Comment by benhoyt** [comment]
Thanks. I'll take a look at it there first.
