### ISSUE TITLE
Pull ? long file name on windows

### ISSUE THREAD

**Issue by yoyoprs** [benhoyt/scandir#59]
On long file names (+ 255 characters) on windows, it is impossible to browse folders. We can bypass this behavior by adding the prefix: \\?\.
It would be interesting to implement it no ? :)

see:http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows

error example: 

```
for obj in scandir.scandir(bpath):
OSError: [Errno 3] The system cannot find the path specified: u'c:\\users\\****\\desktop\\data\\l\xe9b\xe04\\igore\\test\\BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.pdfffffffff'
```

**Comment by benhoyt** [comment]
Yeah, I would love it if all Python path functions seamlessly added the `\\?\` prefix for you if you gave it a long path. However, I guess for simplicity and/or historical reasons, Python doesn't do this -- it leaves it up to the user. For example, I'm pretty certain you'd get the same behavior as above using `os.listdir()`, unless you added the `\\?\` prefix yourself.

**Comment by tjguk** [comment]
The main reason is that \\?\ can't be used with relative paths. (And
only with unicode paths, too). So you can't arbitrarily apply it to all
Python paths.

**Comment by benhoyt** [comment]
@tjguk Are you referring to the reason Python doesn't support this magically? Thanks for the info.

**Comment by tjguk** [comment]
Yes
