### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by prashanthpai** [benhoyt/scandir#61]
The following exception is raised during processing entries returned by `scandir.walk()`

~~~
Traceback (most recent call last):
  File "./reproducer.py", line 39, in <module>
    o = path.replace(dirpath, 'blah')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 16: ordinal not in range(128)
~~~

**Scandir version**: Current master branch (03d8b14b9c25543cbf26e0351935c83f658f701d)

```sh
# python -V
Python 2.7.5
# uname -a
Linux saio 3.18.7-100.fc20.x86_64 #1 SMP Wed Feb 11 19:01:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Here is a sample reproducer:
```python
#!/usr/bin/env python
import os
import random
import scandir


# From openstack swift functional tests.
def create_utf8_name(length=None):
    if length is None:
        length = 15
    else:
        length = int(length)

    utf8_chars = u'\uF10F\uD20D\uB30B\u9409\u8508\u5605\u3703\u1801'\
                 u'\u0900\uF110\uD20E\uB30C\u940A\u8509\u5606\u3704'\
                 u'\u1802\u0901\uF111\uD20F\uB30D\u940B\u850A\u5607'\
                 u'\u3705\u1803\u0902\uF112\uD210\uB30E\u940C\u850B'\
                 u'\u5608\u3706\u1804\u0903\u03A9\u2603'
    return ''.join([random.choice(utf8_chars)
                    for x in xrange(length)]).encode('utf-8')


# Create a directory with UTF8 name
dirname = create_utf8_name()
dirpath = os.path.join('/tmp/reproducer', dirname)
os.makedirs(dirpath)

# This passes
for (path, dirs, files) in os.walk(dirpath):
    print path
    o = path.replace(dirpath, 'blah')
    print o

# This fails
for (path, dirs, files) in scandir.walk(dirpath):
    print path
    o = path.replace(dirpath, 'blah')
    print o
```

**Comment by prashanthpai** [comment]
I commented out [these two lines](https://github.com/benhoyt/scandir/blob/v1.2/scandir.py#L669-L670) in the code and it seems to make the issue go away. However, I don't know if it's the right fix.

**Comment by haypo** [comment]
This issue is not related to scandir, but how you handle Unicode. On the second line "o = path.replace(dirpath, 'blah')", path type is Unicode, whereas dirpath type is bytes.

Either you should encode path to bytes, or decode dirpath to Unicode.

**Comment by prashanthpai** [comment]
I see. But I still wonder why this behavior is not seen when `os.walk` is used and is specific to `scandir.walk`

**Comment by benhoyt** [comment]
Yeah, this is happening because on Python 2.x scandir.walk() doesn't exactly copy os.walk()'s unicode handling. See [this comment](https://github.com/benhoyt/scandir/issues/54#issuecomment-168427430) on issue 54 for more details. 

So on the `path.replace()` line, `path` is actually Unicode, even though you've passed bytes into `scandir.walk()`. So what's happening is:

    o = path_unicode.replace(dirpath_utf8_bytes, b'blah')

And replace is trying to treat `dirpath_utf8_bytes` as ASCII and "upgrade" it to unicode, which fails.

Bytes path handling is only super-broken on Windows, so maybe I should change that test at the bottom of `scandir.py` to:

    if IS_PY3 or sys.platform != 'win32':
        # normal walk
    else:
        # convert-to-unicode walk

Or you could just work around this difference as Victor suggest.

**Comment by prashanthpai** [comment]
@benhoyt Thanks for the explanation. I have incorporated the workaround suggested by Victor in my code. But there are few other places in our codebase where the same issue can be hit and it's quite hard to have 100% coverage in tests. Although, I'm not a big fan of this - I have also sent https://github.com/benhoyt/scandir/pull/62 to make `scandir.walk` mimic `os.walk` behavior so that it can almost always be a drop-in replacement.

**Comment by benhoyt** [comment]
Okay, thanks. Closing this in favour of https://github.com/benhoyt/scandir/pull/62
