### ISSUE TITLE
scandir on python 2.7.10 is causing a StopIteration on *one* directory only

### ISSUE THREAD

**Issue by bschollnick** [benhoyt/scandir#65]
Ben,

I am using this code successfully on a variety of folders (it's part of a web server).  But for some reason, a few days ago, it started to pop a StopIteration error on (so far) only one directory.  Please note, this directory has worked fine in the past with scandir.

The directory has currently 2804 items (files + subdirectories).  

path, dirs, files = next(scandir.walk(scan_directory))

<rant>
I just tried isolating it to a particular set of files or directories, but moving them to a subdirectory, and then slowly moving them back.  And the issue has stopped.
</rant>

This issue has occurred consistently for 3 days in this one directory, so I'm not sure why it's being bashful now.  

I'm going to file the issue, in case it returns, and to let you know what was happening.  
I'll close it, but if for some reason I can't, please feel free to close the issue.

**Comment by bschollnick** [comment]
As indicated it fixed itself during the troubleshooting phase, as I was moving files & directories around.  No code changes were made.

**Comment by benhoyt** [comment]
Very strange -- I haven't seen this before. Let me know if you see any similar problems in the future.

**Comment by bschollnick** [comment]
I've run into it again, but I see what is happening.  

This can happen if the directory that you are running scandir on existed, and then was renamed...
