### ISSUE TITLE
Can next(scandir_result) and next(scandir_result).stat() raise an exception?

### ISSUE THREAD

**Issue by giampaolo** [benhoyt/scandir#66]
Hello. I will soon introduce scandir support into pyftpdlib. 
Given `ls = scandir('.')`:

- should I expect an exception on `next(ls)`? What kind?
- should I expect an exception on `next(ls).stat()`? What kind?

Thanks.

**Comment by benhoyt** [comment]
Yes, both `next(ls)` and `DirEntry.stat()` can raise an `OSError` exception. There's a bit more info about exception handling of `DirEntry` methods in PEP 471 [here](https://www.python.org/dev/peps/pep-0471/#notes-on-exception-handling).

**Comment by giampaolo** [comment]
Thanks. Can `next(ls)` also raise unicode related errors?

**Comment by benhoyt** [comment]
I think it's *possible*, because for example creating a `DirEntry` object on Linux does a decode from bytes to unicode, so if there are non-UTF8 filenames on the file system, it'll raise a `UnicodeError`. But should be extremely unlikely.

**Comment by giampaolo** [comment]
Thanks, that was very useful info. I appreciate it.
