### ISSUE TITLE
Can't detect instance of type DirEntry on Python 2.7

### ISSUE THREAD

**Issue by clawsoon** [benhoyt/scandir#70]
I'm trying to add a clause to my JSONEncoder.default override that'll allow me to JSON-encode DirEntry objects.  However, I can't figure out how to detect the DirEntry object type without the hack of creating a temporary file that's suggested here:

https://bugs.python.org/issue28530#msg279840

Any chance the Python 2.7 version of scandir could have scandir.DirEntry exposed?

Thanks!

**Comment by benhoyt** [comment]
I'm not necessarily opposed to adding this (seeing Python 3.6 has), but I wonder what's the use case for serializing `DirEntry` objects? You can't really re-create them, and the contents of a given directory may have changed by the time you try in any case. Is it more just for debugging?

In the meantime, you could use the `NamedTemporaryFile` hack in the bugs.python.org comment you linked to, or another duck-typing hack like this:

    def dir_entry_encoder(obj):
        if isinstance(getattr(obj, 'name', None), str) and callable(getattr(obj, 'is_dir', None)):
            return obj.name
        return obj

**Comment by clawsoon** [comment]
Use case: In this case, I'm generating thumbnails for a directory tree after a browser request is made, with AJAX polling to update the completion status of the thumbnails.  The list of thumbnails to be generated, with metadata about the images they're being generated from (e.g. name, mtime) goes back to the browser as part of a JSON-encoded data dict that also carries other info.  It's easy enough to explicitly convert the DirEntry objects to dicts before adding them to the data dict, but I thought it would be nice to give the JSON encoder the ability to do it.

The duck-typing hack you've suggested should work well enough, thanks.

**Comment by benhoyt** [comment]
Cool, thanks. I'll leave this open in any case.

**Comment by benhoyt** [comment]
This should be fixed with PR #93
