### ISSUE TITLE
can't install with pip

### ISSUE THREAD

**Issue by mason2012** [benhoyt/scandir#82]
python version: 2.7
Traceback:
   ...    
   MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
   TypeError: __call__() takes exactly 2 arguments (1 given)

It happend when I install jupyter with pip. I tried to download md5 file and install scandir using command 'python setup.py install'. But it can't work.

**Comment by benhoyt** [comment]
This sounds like a pip bug. From [this thread](http://stackoverflow.com/questions/42029545/pip-is-error-typeerror-call-takes-exactly-2-arguments-1-given) (the second answer with 50+ points), it looks like pip has already fixed it, and you should upgrade pip with the following:

    python -m pip install --upgrade --force pip

**Comment by mason2012** [comment]
Thanks for your reply. It can't work with the command you give. But the second answer by RobotNerd worked though I don't know why. Anyway, thanks for your information.
