### ISSUE TITLE
Provide Windows wheels

### ISSUE THREAD

**Issue by segevfiner** [benhoyt/scandir#83]
It would be helpful if scandir had wheels for Windows on PyPI.

I encountered the need for Windows wheels since IPython depends on pathlib2, for Python versions that don't have it in the standard library, which in turn depends on scandir.

You can always use Appveyor if you don't have a Windows computer to do it yourself manually. See [Supporting Windows using Appveyor](https://packaging.python.org/appveyor/)

**Comment by SethMichaelLarson** [comment]
This would be a great thing to provide.

**Comment by benhoyt** [comment]
Thanks for the suggestion! Finally done with version 1.6: https://pypi.python.org/pypi/scandir
