### ISSUE TITLE
Failed to build scandir

### ISSUE THREAD

**Issue by TMWagner** [benhoyt/scandir#85]
Attempting to install Azure CLI 2.0, I've encountered an error that debugging seems to narrow down to a problem with "scandir". 
To narrow down whether the problem is with the CLI installer or with scandir, the following command were suggested. 
`curl -O https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
sudo pip install virtualenv
virtualenv myenv
source myenv/bin/activate
pip install scandir`

That resulted in an error (the same one encountered with the CLI installer) as follows: 

> 
Thomass-MacBook-Pro:~ thomaswagner$ curl -O https://bootstrap.pypa.io/get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1558k  100 1558k    0     0  5104k      0 --:--:-- --:--:-- --:--:— 7018k

Thomass-MacBook-Pro:~ thomaswagner$ sudo python get-pip.py
Password:
The directory '/Users/thomaswagner/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/thomaswagner/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 654kB/s
Collecting setuptools
  Downloading setuptools-36.0.1-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 481kB 1.6MB/s
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 5.8MB/s
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.1 setuptools-36.0.1 wheel-0.29.0
Thomass-MacBook-Pro:~ thomaswagner$ sudo pip install virtualenv
The directory '/Users/thomaswagner/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/thomaswagner/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting virtualenv
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 426kB/s
Installing collected packages: virtualenv
Successfully installed virtualenv-15.1.0
Thomass-MacBook-Pro:~ thomaswagner$ virtualenv myenv
New python executable in /Users/thomaswagner/myenv/bin/python
Installing setuptools, pip, wheel...done.
Thomass-MacBook-Pro:~ thomaswagner$ source myenv/bin/activate
(myenv) Thomass-MacBook-Pro:~ thomaswagner$ pip install scandir
Collecting scandir
  Downloading scandir-1.5.tar.gz
Building wheels for collected packages: scandir
  Running setup.py bdist_wheel for scandir ... error
  Complete output from command /Users/thomaswagner/myenv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/f4/0zjyjj1d6db6z__bfq55m6rm0000gn/T/pip-build-AuAhdj/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/f4/0zjyjj1d6db6z__bfq55m6rm0000gn/T/tmpvtFbzqpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  copying scandir.py -> build/lib.macosx-10.6-x86_64-2.7
  running build_ext
  building '_scandir' extension
  creating build/temp.macosx-10.6-x86_64-2.7
  gcc -fno-strict-aliasing -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Applications/MAMP/Library/include/python2.7 -c _scandir.c -o build/temp.macosx-10.6-x86_64-2.7/_scandir.o
  _scandir.c:14:10: fatal error: 'Python.h' file not found
  #include <Python.h>
           ^
  1 error generated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for scandir
  Running setup.py clean for scandir
Failed to build scandir
Installing collected packages: scandir
  Running setup.py install for scandir ... error
    Complete output from command /Users/thomaswagner/myenv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/f4/0zjyjj1d6db6z__bfq55m6rm0000gn/T/pip-build-AuAhdj/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/f4/0zjyjj1d6db6z__bfq55m6rm0000gn/T/pip-Oo02mY-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/thomaswagner/myenv/include/site/python2.7/scandir:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-2.7
    copying scandir.py -> build/lib.macosx-10.6-x86_64-2.7
    running build_ext
    building '_scandir' extension
    creating build/temp.macosx-10.6-x86_64-2.7
    gcc -fno-strict-aliasing -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Applications/MAMP/Library/include/python2.7 -c _scandir.c -o build/temp.macosx-10.6-x86_64-2.7/_scandir.o
    _scandir.c:14:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/Users/thomaswagner/myenv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/f4/0zjyjj1d6db6z__bfq55m6rm0000gn/T/pip-build-AuAhdj/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/f4/0zjyjj1d6db6z__bfq55m6rm0000gn/T/pip-Oo02mY-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/thomaswagner/myenv/include/site/python2.7/scandir" failed with error code 1 in /private/var/folders/f4/0zjyjj1d6db6z__bfq55m6rm0000gn/T/pip-build-AuAhdj/scandir/
(myenv) Thomass-MacBook-Pro:~ thomaswagner$

**Comment by benhoyt** [comment]
I believe this is because you need to install the Python development libraries/headers before building libraries. This would happen with any library, not just scandir. See https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory (though I'm not sure how to fix it on macOS.)

**Comment by TMWagner** [comment]
Is there an installer for scandir for the Mac platform - Or instructions?

**Comment by benhoyt** [comment]
Not that I know of, sorry!

**Comment by code4clouds** [comment]
I installed ```python-pip``` then```pip install scandir``` followed by ```pip install --upgrade pip```.  It worked for me after that with the curl command in the page (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) .

**Comment by benhoyt** [comment]
Going to close this issue per above.

**Comment by spencerbartz** [comment]
The above solution did not work for me and this has become a 4 hour nightmare of trying partial solutions from various forums. Any help would be much appreciated.

I am trying to install scandir using `sudo pip install scandir` so I can install IPython using `sudo pip install ipython` but both result in the same error
```
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c _scandir.c -o build/temp.linux-x86_64-2.7/_scandir.o
    _scandir.c:14:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

I do not wish to (and don't know how) to change the gcc command being used here.
I cannot find any `Python.h` and I am a sudo user.

Environment
```
python 2.7.5 on RHEL 
Operating System: Red Hat Enterprise Linux
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.4:GA:server
Kernel: Linux 3.10.0-693.2.2.el7.x86_64
Architecture: x86-64
pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)
```
Output of `whereis python` 
```
 /usr/bin/python /usr/bin/python2.7 /usr/lib/python2.7 /usr/lib64/python2.7 /etc/python /usr/include/python2.7 /usr/share/man/man1/python.1.gz
```

**Comment by bschollnick** [comment]
I’m not sure that this will help…

But double check the command line utilities are installed for Xcode.

1) Start up Xcode
2) See if it prompts to install “Additional required components”
	a) If so, install them.

I’ve seen this fix issues in the past with GCC compilation…

	- Benjamin

**Comment by benhoyt** [comment]
@spencerbartz per my message above:

> I believe this is because you need to install the Python development libraries/headers before building libraries. This would happen with any library, not just scandir. See https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory (though I'm not sure how to fix it on macOS.)

@bschollnick note that @spencerbartz is running Linux, so Xcode doesn't apply.

**Comment by spencerbartz** [comment]
@benhoyt 
I've seen and tried everything in that post with no luck.
I am using RHEL so the closest thing in that post was "CentOS"
I'm not experienced with yum or RHEL but my company won't allow Ubuntu for some reason.

Running that command I get this:
```
~$ sudo yum install python27-devel
Loaded plugins: product-id, search-disabled-repos, subscription-manager
No package python27-devel available.
```

**Comment by isaacegglestone** [comment]
I had the same issue and thanks to these posts and one last item I did I resolved it.

I can't believe it was this easy, the fact is the standard redhat distro doesn't have gcc installed and so scandir fails to build and so you end up with this issue.

Here is what solved it for me on Redhat 7.2:

sudo yum install python-devel.x86_64 python27-python-devel.x86_64 gcc

I wasn't even installing Ipython but installing anything that needs to build anything using gcc with pip will fail so basically "pip install AnythingEsefulRequiringUncompiledDevTools" will fail on redhat 7.2/7.4

Of course redhat will say this is obvious but when the real error message isn't gcc not found but 
Failed to build scandir its a bit confusing..

**Comment by gstream1** [comment]
I am using RHEL 7 and can confirm that:
sudo yum install python-devel.x86_64 python27-python-devel.x86_64 gcc
worked for me to be able to run: sudo pip install azure-datalake-store. Thank you a bunch for this solve @isaacegglestone.

**Comment by basiljose1** [comment]
**Install Common Dependencies**

`sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev`

**Comment by singkwan** [comment]
Install common dependencies code from basiljose1 worked!
