### ISSUE TITLE
Inode is unsigned?

### ISSUE THREAD

**Issue by nh2** [benhoyt/scandir#87]
Potential issue here: https://github.com/benhoyt/scandir/commit/f092447c531894d418d04df31413a416ed2c9b6f#commitcomment-24385573

Is this a bug?

**Comment by benhoyt** [comment]
Thanks! I've fixed in 20022fe7133d506beba95a50bfa77564938b4951 and I'll aim to push out a PyPI release at some point in the next few days.

**Comment by nh2** [comment]
@benhoyt With scandir being part of Python 3, does that need some special action or will it be taken care of automatically?

**Comment by benhoyt** [comment]
Not quite sure what you're referring to? As you noted, it's been fixed in CPython already (https://github.com/python/cpython/commit/0f6d73343d342c106cda2219ebb8a6f0c4bd9b3c), and looks like it will be backported to 3.6 too.
