### ISSUE TITLE
Seeing unnamed fields in stats under python 2.7 w/scandir 1.6 (MOSX)

### ISSUE THREAD

**Issue by bschollnick** [benhoyt/scandir#91]
Under Mac OS X, with python 2.7 and candid 1.6, I'm seeing unnamed fields if I dir(entry.stat).  

I can still read entry.stat.st_ctime or entry.stat.st_mtime, etc.  So this appears to be cosmetic, but annoying.

scandir.stat_result(st_mode=33188L, st_ino=11060996L, st_dev=16777222L, st_nlink=1L, st_uid=501L, st_gid=20L, st_size=17350L, unnamed field=1500741095, unnamed field=1439669534, unnamed field=1439669534)

**Comment by benhoyt** [comment]
As this seems to be just cosmetic, closing for now. Feel free to reopen with a proposed fix if this is breaking code. Thanks for the report!
