### ISSUE TITLE
unsupported option '-fopenmp';error: command 'cc' failed with exit status 1 when install spams

### ISSUE THREAD

**Issue by DrRambo** [benhoyt/scandir#92]
Hello everyone, I've been trying to install spams on OSX 10.12.6. It's python 2.7. Here is output

> python setup.py install
running install
running build
running build_py
running build_ext
building '_spams_wrap' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I. -Ispams/linalg -Ispams/prox -Ispams/decomp -Ispams/dictLearn -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I/usr/include/python2.7/ -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c spams_wrap.cpp -o build/temp.macosx-10.12-intel-2.7/spams_wrap.o -DNDEBUG -DUSE_BLAS_LIB -fPIC -fopenmp -m32
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
error: command 'cc' failed with exit status 1

**Comment by benhoyt** [comment]
I think this is a spams problem and not scandir -- was this intended for the http://spams-devel.gforge.inria.fr/ project?

**Comment by DrRambo** [comment]
@benhoyt Yes, it's for spams. I can install it in linux, but not work in OSX.
