### ISSUE TITLE
'module' object has no attribute 'DirEntry' when an old scandir version is present

### ISSUE THREAD

**Issue by zanglang** [benhoyt/scandir#97]
Kind of an edge case, but in a certain environment where a scandir<1.7 version is present importing scandir==1.7 will throw an Exception due to the recent DirEntry change.

To reproduce, install scandir==1.6 in an empty virtualenv and import scandir==1.7 packaged in a zip.
```
(dummy)  /mnt/c/Users/user/Projects/test_scandir  pip freeze
scandir==1.6
(dummy)  /mnt/c/Users/user/Projects/test_scandir  unzip -l deps.zip
Archive:  deps.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2018-03-23 17:41   scandir-1.7.dist-info/
     8505  2018-03-23 17:41   scandir-1.7.dist-info/DESCRIPTION.rst
        4  2018-03-23 17:41   scandir-1.7.dist-info/INSTALLER
     9603  2018-03-23 17:41   scandir-1.7.dist-info/METADATA
     1148  2018-03-23 17:41   scandir-1.7.dist-info/metadata.json
      723  2018-03-23 17:41   scandir-1.7.dist-info/RECORD
       17  2018-03-23 17:41   scandir-1.7.dist-info/top_level.txt
      105  2018-03-23 17:41   scandir-1.7.dist-info/WHEEL
    24116  2018-03-23 17:41   scandir.py
    18431  2018-03-23 17:41   scandir.pyc
    62536  2018-03-23 17:41   _scandir.so
---------                     -------
   125188                     11 files
(dummy)  /mnt/c/Users/user/Projects/test_scandir  env PYTHONPATH=deps.zip python -c "import scandir"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-5QYZ0t/scandir/scandir.py", line 571, in <module>
    scandir = scandir_python
AttributeError: 'module' object has no attribute 'DirEntry'
```

**Comment by zanglang** [comment]
Seems that that was an artifact in _scandir.so when pip installing scandir, perhaps I'll need to turn off debug symbols.

```
# strings deps/_scandir.so | grep pip-build
/tmp/pip-build-psTFR0/scandir
```

I'll try and reproduce this again in a clean environment.

**Comment by JackDandy** [comment]
This is not edge case.  If a regular system already has a version of _scandir.pyd installed in site-packages that predates the newly added feature the exposes DirEntry type, then scandir.py will outright fail.

**Comment by JackDandy** [comment]
If a regular system already has a version of _scandir.pyd installed in site-packages that predates the newly added feature the exposes DirEntry type, then scandir.py will outright fail.

A case is where the latest Scandir is bundled within a project.

Scandir will import _scandir from the system.  If the project bundles 1.7 and the system has 1.6 - then it will fail.

Reverting to c3592eeab71e95f5314d17c75fd4390fad8ccda5 solved the issue.

Placing a try block around the newly exposed DirEntry lines would mitigate.

**Comment by splattadat** [comment]
This is east to reproduce where 1.6 is installed using pip, and a project uses version 1.7 in separation.

**Comment by zanglang** [comment]
Turns out the having multiple versions was a red herring, the root cause was that Python's zipimport does not allow importing dynamic modules.

So in my case, we would have scandir==1.7 Python code in the zip attempting to do "import _scandir" and importing scandir==1.6 in the virtualenv, which should result in an unknown state anyway. I'll close this ticket now.
